version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install time
      - export BUCKET=ungerw-testingcicdlambda-ap-south-1
      - aws cloudformation package --template-file template.yaml --s3-bucket testingcicdlambda --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml